spring:
  application:
    name: cherry

  flyway:
    enabled: true
    baseline-on-migrate: true

  datasource:
    url: jdbc:mysql://localhost:3307/cherry?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: cherry
    password: ${DB_PASSWORD:cherrypw1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email

vapid:
  public-key: ${VAPID_PUBLIC_KEY:BJBlTgRDS41vrnXzyEgY9ipyNWXqoNFW4rWg_4xbXQJT42ZfUalwOWtd1_jWQx3lSKi4ktcA-mmphK3V1POSvOE}
  private-key: ${VAPID_PRIVATE_KEY:o2GwFffdHUoX-heR3Ru0Yzl3NA1XaoclTQqFI6omFnI}
  subject: mailto:dev@cherry.local

app:
  upload-dir: ${UPLOAD_DIR:uploads}

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
